[package]
name = "audio-analysis"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3.1"
rustfft = "6.0.1"
wav = "1.0.0"
